### ISSUE TITLE
AttributeError: module 'osmnx' has no attribute 'get_nearest_edges'

### ISSUE THREAD

**Issue by fblamanna** [matteoboh/mobility_emissions#2]
Tried to run the example__taxi_Beijing with OSMnx 1.2.1 installed and find the following error in 3. Points snapping:

```
AttributeError                            Traceback (most recent call last)
Input In [15], in <cell line: 3>()
      1 from mobair import mapmatching
----> 3 tdf_final = mapmatching.find_nearest_edges_in_network(road_network, tdf_mapped, return_tdf_with_new_col=True)
      4 print(tdf_final.head())

File ~/Dropbox/Progetti/SUMO/ScikitMobility/mobility_emissions-master/mobair/mapmatching.py:97, in find_nearest_edges_in_network(road_network, tdf, return_tdf_with_new_col)
     94 vec_of_latitudes = np.array(tdf['lat'])
     96 # for each (lat,lon), find the nearest edge in the road network:
---> 97 array_of_nearest_edges = ox.get_nearest_edges(road_network, X=vec_of_longitudes, Y=vec_of_latitudes,
     98 											 method='balltree')
     99 ###
    100 # method (str {None, 'kdtree', 'balltree'}) – Which method to use for finding nearest node to each point.
    101 # If None, we manually find each node one at a time using osmnx.utils.get_nearest_node and haversine.
    102 # If ‘kdtree’ we use scipy.spatial.cKDTree for very fast euclidean search.
    103 # If ‘balltree’, we use sklearn.neighbors.BallTree for fast haversine search.
    104 ###
    106 list_of_nearest_edges = [(edge[0],edge[1],edge[2]) for edge in array_of_nearest_edges]

AttributeError: module 'osmnx' has no attribute 'get_nearest_edges'
```

I guess that OSMnx 1.2.1 - get.nearest_edges()/nodes() changed in distance.nearest_edges()/nodes() with different keywords

**Comment by matteoboh** [comment]
Dear @fblamanna, thanks for pointing this out.
Yes, this is definitely due to the new version of OSMnx. The easiest and fastest way of solving this is that you use the `environment.yml` file I just added to the repo (together with a few instructions in the _Requirements_ section of the README) to create a conda environment that has all the libraries (and versions) you need. In this way, you should be able to run the example notebooks without any issues.

In the meantime, we will update the methods in this repository to make them consistent with OSMnx 1.2.1

Thank you again, and please let us know if you encounter any other problems.

**Comment by SamsonDada** [comment]
Dear @matteoboh, thanks for the response above. I had same issue. I use OSMnx 1.2.3.

I looked in the mapmatching.py and edited as shown below following the documentation here (https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.distance ) and it worked fine.

# for each (lat,lon), find the nearest node in the road network:
	list_of_nearest_nodes = ox.nearest_nodes(road_network, X=vec_of_longitudes, Y=vec_of_latitudes)
    
    ####
    
    # If the graph is projected, this uses a 'k-d tree' for euclidean nearest neighbor search, 
    # which requires that scipy is installed as an optional dependency.
    # we use scipy.spatial.cKDTree for very fast euclidean search.
    
    # If it is unprojected, this uses a 'ball tree' for haversine nearest neighbor search, 
    # which requires that scikit-learn is installed as an optional dependency.
    # we use sklearn.neighbors.BallTree for fast haversine search.
    
	####

# for each (lat,lon), find the nearest edge in the road network:
	array_of_nearest_edges = ox.nearest_edges(road_network, X=vec_of_longitudes, Y=vec_of_latitudes)
    
	####
    
    # If the graph is projected, this uses a 'k-d tree' for euclidean nearest neighbor search, 
    # which requires that scipy is installed as an optional dependency.
    # we use scipy.spatial.cKDTree for very fast euclidean search.
    
    # If it is unprojected, this uses a 'ball tree' for haversine nearest neighbor search, 
    # which requires that scikit-learn is installed as an optional dependency.
    # we use sklearn.neighbors.BallTree for fast haversine search.
    
	####

@matteoboh, What's your take on this?
Thanks

**Comment by matteoboh** [comment]
Dear @SamsonDada, thank you very much for pointing this out again, and thanks for the suggestion.
I just modified the methods in the module `mapmatching.py` so that now they are consistent with newer versions of osmnx. I also updated the `environment.yml` file accordingly.

Please let us know if you encounter any other issues!

**Comment by SamsonDada** [comment]
Dear@matteoboh, thanks for your response.
I noticed the module - fitting.py  used in the very last cell is missing in the mohair folder.
I got this error:

ModuleNotFoundError: No module named 'fitting'

Thanks

**Comment by matteoboh** [comment]
Hello @SamsonDada, please have a look at issue #3. Thank you and sorry for the late reply.
